### PR TITLE
doc: distro.tex: fix typos

### PR DESCRIPTION
**Pull request by r-mckay**
This commit fixes some typos in the text of distro.tex.
This set of fixes covers the chapters 1, 2 and 3.
I also suggest to merge this branch into master though this pull request.

### CODE REVIEW

**Comment by gportay** [comment]
Thanks for the review.

I will squash all commits to create the first version. And some parts of Makefile should not be a part of this very first version.

Furthermore, i also have to credit yourself ;)

**Comment by r-mckay** [comment]
Hey @gazoo74 !
How was your workathon? Did you have the time to do what you wanted?

**Comment by gportay** [comment]
@r-mckay, i did something else at workathon :( but I will handle your pr soon. Certainly on Sunday.

**Comment by gportay** [comment]
@r-mckay: you can now rebase you PR on top of master, sorry for the delay

**Comment by r-mckay** [comment]
@gazoo74 done thx :)

**Pull request merged**
